### ISSUE TITLE
Class 'GuzzleHttp\Psr7\Utils' not found

### ISSUE THREAD

**Issue by gemal** [loco/loco-php-sdk#12]
![image](https://user-images.githubusercontent.com/69105/95442987-4e494d00-095c-11eb-821a-ba9527872aa2.png)

loco/loco/src/Http/Request/BodyLocation.php

**Comment by timwhitlock** [comment]
`Guzzle\Psr7\stream_for` is deprecated although admittedly not until 2.0 which my library will probably never depend on. 

My question is why you don't you have `Guzzle\Psr7\Utils::streamFor` available after doing your composer update?

The composer dependency graph looks like this:

```
├──guzzlehttp/guzzle-services ^1.1
│  ├──guzzlehttp/guzzle ^6.2
│  │  ├──guzzlehttp/psr7 ^1.6.1
```

That leaves me with `guzzlehttp/psr7` v1.7.0 installed. What version do you have?

**Comment by timwhitlock** [comment]
Looks like [GuzzleHttp\Psr7\Utils](https://github.com/guzzle/psr7/blob/1.7.0/src/Utils.php) is in the v1.7.0 release, but is not present on [master](https://github.com/guzzle/psr7/tree/master/src), I guess because there is a [1.x branch](https://github.com/guzzle/psr7/tree/1.x/src). I can only presume that the master branch will be version 2, but whatever the reason I'd like to know why my composer.json doesn't provide the correct version. 

Let me know on that. In the mean time I've reverted my master branch to the deprecated function.

**Comment by gemal** [comment]
not sure how to find it
my `Vendor\guzzlehttp\psr7\composer.json ` says
```
    "extra": {
        "branch-alias": {
            "dev-master": "1.6-dev"
        }
    } 
```

if not that how can I find the info you need

**Comment by timwhitlock** [comment]
Just do `composer show -i | grep guzzlehttp`

**Comment by timwhitlock** [comment]
I guess the bottom line here is that if `guzzlehttp/guzzle` depends on `guzzlehttp/psr7 ^1.6.1` then my library can't guarantee you have 1.7. Possibly you have something else installed that requires a lower maximum version. 

I'll make sure the next release uses the old, deprecated function. In the mean time you can either track the master or roll back to 2.0.7 of this library.

**Comment by gemal** [comment]
guzzlehttp/guzzle                  6.5.5              Guzzle is a PHP HTTP client library
guzzlehttp/guzzle-services         1.1.3              Provides an implementation of the Guzzle Command library that uses Guzzle service descriptions to ...
guzzlehttp/promises                v1.3.1             Guzzle promises library
guzzlehttp/psr7                    1.6.1              PSR-7 message implementation that also provides common utility methods

**Comment by timwhitlock** [comment]
Ok, well with `guzzle-services 1.1.3` (which you have) you should get `guzzlehttp/psr7 1.7.0` when you do a composer update unless some other library is constraining this to a lower version. Is this the case? Have you done an update?

Anyway, I've rolled the change back in master and have no plans to re-instate it.

**Comment by gemal** [comment]
@timwhitlock could you make a new release with the already commited "fix" included?

**Comment by gemal** [comment]
thank you!

**Comment by digitv** [comment]
Hi! With latest version (at the moment 2.0.10) this problem reproduces, Guzzle packages versions are below
```
guzzlehttp/guzzle                7.4.1      Guzzle is a PHP HTTP client library
guzzlehttp/guzzle-services       1.3.1      Provides an implementation of the Guzzle Command library...
guzzlehttp/promises              1.5.1      Guzzle promises library
guzzlehttp/psr7                  2.1.0      PSR-7 message implementation that also provides common utility methods
```
Please roll-up a new version with this fix, besides "dev-master" works as expected.

**Comment by timwhitlock** [comment]
Yeh, this dependency has proved to be a real pain. Maybe @gemal could confirm that [the fix](https://github.com/loco/loco-php-sdk/commit/8483cf3b38c0557717f1888d6516e47d926708e0#diff-752d6ccf4f7ff7d7cee8a17a15530790e1382bc10cd5bb2f624121648ba9c9bb) now on master is working for his use case also?

**Comment by gemal** [comment]
I have not gotten any problems
