### ISSUE TITLE
Error with self-signed SSL certificate

### ISSUE THREAD

**Issue by amigian74** [loco/loco-php-sdk#13]
Hello,

when running an import (or even the authentication verification) I get the following error:

`There was an error executing the authVerify command: cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://localise.biz/api/auth/verify`

**Comment by timwhitlock** [comment]
The certificate chain on localise.biz contains an intermediate certificate, but it is valid. 

See our ssl labs server test here: https://www.ssllabs.com/ssltest/analyze.html?d=localise.biz
It currently has a score of **A+**

It's possible you need to update your system to recognise this chain. I don't have any error with my local cURL or via PHP and and no other reports from customers about broken API access.

**Comment by amigian74** [comment]
Ok thx.
