### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by digitv** [loco/loco-php-sdk#14]
Hi! Could you add support of latest PHP version ( ^8.0 ) ?
We are using your SDK in our project ( with Laravel 8) but we couldn't update to the latest PHP.

**Comment by StevenAvelino24** [comment]
Would it be possible to release the change made in d8904c8 ?
The package is still not PHP 8 compliant unless we get the master branch

**Comment by timwhitlock** [comment]
Can you confirm that the change works for you. 

I've only run the phpunit tests under PHP8. It's not tested with Laravel as per the original request.

**Comment by digitv** [comment]
> Can you confirm that the change works for you.
> 
> I've only run the phpunit tests under PHP8. It's not tested with Laravel as per the original request.

Hi! Package works for our project as good as before on PHP 7.4. Off course we are using not all the functionality, but upload/download/getting_locales seems to be OK, no exceptions
