### ISSUE TITLE
Option to disable verification

### ISSUE THREAD

**Issue by amigian74** [loco/loco-php-sdk#15]
Hi,

For several weeks I get the following error:

```There was an error executing the authVerify command: cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://localise.biz/api/auth/verify```

Is there something I can do. If not it would be great if I can disable the verification for the Guzzle-Http client.

**Comment by timwhitlock** [comment]
I think config.json should be allowed to pass in any Guzzle config, not just this one. I'll take a look.

I note that  you already asked about this in issue #13. The best solution would still be to update your system to accept my certificate chain. Obviously disabling SSL verification is not something I can ever recommend.
