### ISSUE TITLE
symfony 4

### ISSUE THREAD

**Issue by gemal** [loco/loco-php-sdk#6]
can you update so that you package also supports symfony 4?

**Comment by timwhitlock** [comment]
Is this as simple as changing composer.json to include 4.0, like: `"symfony/console": "~2.5|~3.0|~4.0"` ?

**Comment by gemal** [comment]
I think so

**Comment by timwhitlock** [comment]
Ok then. [Done in master](https://github.com/loco/loco-php-sdk/commit/86417a6f0414a6e4940f77bd0cafc00d7a34e116). Would you mind checking it for me?

**Comment by gemal** [comment]
Yes it works. Can you release a new version?

**Comment by timwhitlock** [comment]
Good news.

I won't release a new version for just a single line change. I suggest you track the master branch. I don't generally push unstable code to master.
