### ISSUE TITLE
Document ApiClient magic methods with @method PHPDoc tag

### ISSUE THREAD

**Issue by rulatir** [loco/loco-php-sdk#7]
I can see that examples show usages like `$client->exportLocale(/* ... */);`, but the `ApiClient` class does not define any such methods. This must mean that they are somehow translated to endpoint paths using `__call()` automagic.

Please document these magic methods using `@method` PHPDoc tags so that they will be available for code completion and won't trigger code inspection warnings in modern IDEs.

Alternatively `return new static` instead of `new self` in `ApiClient::factory()` so that one can subclass it and add the missing PHPDoc to the subclass.

**Comment by timwhitlock** [comment]
Thanks for the suggestion. The service definition is completely auto-generated, so I will look into adding `@method` tags as part of that build process.

**Comment by timwhitlock** [comment]
Hi. Would you mind checking out the master branch? I've [added the code hints][1], but I'm "between IDEs" at the moment, so I can't see if they work. 

[1]: https://github.com/loco/loco-php-sdk/commit/2eeb414f1543f1ee52cdf400dd41d9b4158c17f8

**Comment by timwhitlock** [comment]
https://github.com/loco/loco-php-sdk/releases/tag/2.0.1

**Comment by rulatir** [comment]
Great, works like charm, thanks!
