### ISSUE TITLE
For each POST endpoint, document the name of the params array key for request body

### ISSUE THREAD

**Issue by rulatir** [loco/loco-php-sdk#9]
I can see in the example that for the `import` endpoint the correct argument name is `src`, but I cannot figure this out for other POST endpoints (e.g. `flag`) without inspecting the code. The REST API docs just say it should be the request body.

**Comment by timwhitlock** [comment]
I see your point. 

The binding parameter is specific to the SDK (not the API) so that's why it's not documented in the API docs. It wouldn't apply to other client libraries and would be confusing to add it.

Any suggestions how to document this within the SDK? The binding names are in the service.json file, but not sure how to pull that out into something visible.

**Comment by timwhitlock** [comment]
In retrospect, I should have stuck to a common name, like "body" but hard to change that without breaking backward compatibility.

**Comment by rulatir** [comment]
That seems really hard! `@method` doesn't accept multiline description. Maybe emit actual methods forwarding to `return $this->__call(__FUNCTION__,func_get_args());` and give them full docblocks?

**Comment by rulatir** [comment]
Other than that, maybe mention the issue in the README and point at service.json. It's readable just fine.

**Comment by timwhitlock** [comment]
I think I will just add a note in the API docs that says the official SDK binds to `src` but to read the docs if you use another library.

**Comment by timwhitlock** [comment]
Hey. 
I decided the easiest thing by far was to standardize all request body bindings to use the key `data`. I've documented this in the API docs with a line that says:

> Loco's official SDK binds the request body to the "data" parameter. Check the documentation for other libraries.

Effective from 1.0.20 of the API (2.0.2 of the SDK)
https://localise.biz/api/docs/changelog#010020

Note that any previous names  (like `src`) will continue to work as a fallback.

**Comment by rulatir** [comment]
It would seem that the `src` fallback stopped working after all in dev-master. Should I have explicity installed 2.0.2? It's not a problem now because I fixed my code to use `data`, but you may want a heads up.

(I started receiving 422 about ill-formed .po and thought it was a different issue, so I wrote to you from the Contact form and only then I pulled my email and saw this).

**Comment by timwhitlock** [comment]
Thanks for the info. The legacy `src` fallback happens on the back end, so not related to the library being used. However, I can't say why it wasn't working for you. I'll take a look.

**Comment by timwhitlock** [comment]
I've worked it out.

Upgrading the SDK also means changing the client code as you're passing in the 'src' key. I had foolishly assumed that the service description automatically used the right bindings. I will rush a release to fix this as others could be falling foul of this.

**Comment by timwhitlock** [comment]
Master branch has a fix for this. Will release as 2.0.3 asap.
